development: &default
  adapter: postgresql
  database: crownstack
  encoding: utf8
  host: localhost
  min_messages: warning
  username: postgres
  password: postgres
  pool: 2
  # timeout: 5000

test:
  <<: *default
  database: crownstack_test

